version: '3.8'

networks:
  public-network:
    driver: bridge
  ml-network:
    driver: bridge

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - public-network
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      backend:
        condition: service_started

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email ivannikolov007@gmail.com --agree-tos --no-eff-email --force-renewal -d gonext.lol

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - public-network
      - ml-network
    dns:
      - 8.8.8.8
      - 8.8.4.4

  gonext-ml:
    build:
      context: ../gonext-ml
      dockerfile: Dockerfile
    networks:
      - ml-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
