version: '3.8'

networks:
  public-network:
    driver: bridge
  private-network:
    driver: bridge
    internal: true
  ml-network:
    driver: bridge

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - public-network
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      backend:
        condition: service_started

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email ivannikolov007@gmail.com --agree-tos --no-eff-email --force-renewal -d gonext.lol

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - public-network
      - private-network
      - ml-network
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_started
    dns:
      - 8.8.8.8
      - 8.8.4.4

  gonext-ml:
    build:
      context: ../gonext-ml
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
    networks:
      - ml-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_started

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - private-network
    expose:
      - "5432"

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    networks:
      - private-network
    expose:
      - "6379"

volumes:
  postgres-data:
  redis-data:
